name: Mirror to New Account

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to nishan-paul-hello
        env:
          MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
        run: |
          git remote add destination https://x-access-token:${MIRROR_PAT}@github.com/nishan-paul-hello/${{ github.event.repository.name }}.git
          git push destination "refs/remotes/origin/*:refs/heads/*" --force --tags --prune
